"""empty message

Revision ID: cecf589b07b9
Revises: efd12e01734c
Create Date: 2018-08-14 09:38:01.809000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cecf589b07b9'
down_revision = 'efd12e01734c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_request_target_date', table_name='request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_request_target_date', 'request', ['target_date'], unique=False)
    # ### end Alembic commands ###
